name: fossil_rush
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  shared_preferences: ^2.2.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/characters/tard/
    - assets/characters/cole/
    - assets/characters/mort/
    - assets/characters/mono/
    - assets/characters/kuro/

  fonts:
    - family: Pixel
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

